# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_src',
            field=models.CharField(default='/songs/WildestDreams_1989_TaylorSwift.mp3/', max_length=255),
            preserve_default=False,
        ),
    ]
