# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web0', '0004_auto_20161124_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_src',
            field=models.FileField(upload_to=''),
        ),
    ]
